package task;

import java.util.*;

/**
 * Do not edit this file. 
 */

public abstract class StockAPI {
  public static StockAPI API;

  /**
   * Returns an array of the IDs of the ShopItems that are
   * currently in stock.
   * 
   * Example usage:
   *   int[] ids = StockAPI.API.getStockIds();
   * 
   * @return an array of ShopItem IDs.
   */
  public abstract int[] getStockIds();
}
