package task;

import java.util.*;

/**
 * Do not edit this file. 
 */

public class ScrollBarMenu {
  public final static Map<String, Integer> menucard = new HashMap<String, Integer>() {{
    put("Tuborg", 30);
    put("ScrollBar Punch", 30);
    put("Cola", 20);
    put("Carrot Juice", 56);
    put("Tequila Shots", 100);
    put("Water", 0);
  }};
}
