package task;

/**
 * Do not edit this file. 
 */

public abstract class ConnectionAPI {
  public static ConnectionAPI API;
  
  /**
   * Returns whether wifi is able to connect at the moment.
   *
   * Example usage:
   *   boolean available = ConnectionAPI.API.isWifiAvailable();
   * 
   * @return true if wifi is available, false otherwise
   */
  public abstract boolean isWifiAvailable();

  /**
   * Returns whether mobile data is able to connect at the moment.
   *
   * Example usage:
   *   boolean available = ConnectionAPI.API.isMobileDataAvailable();
   * 
   * @return true if mobile data is available, false otherwise
   */
  public abstract boolean isMobileDataAvailable();
}
