package task;
import java.util.*;

/**
 * Do not edit this file. 
 */

public abstract class DeviceAPI {
  public static DeviceAPI API;
  
  /**
   * Returns a list of available connections. All names are 
   * lowercase and without spaces.
   *
   * Example usage:
   *   ArrayList<String> connections = DeviceAPI.API.getAvailableConnections();
   * 
   * @return a list of available connections
   */
  public abstract ArrayList<String> getAvailableConnections();
}
